# R Cheatsheet

## Arithmetic operations

In [9]:
2+2  # Addition

[1] 4

In [2]:
2-2  # Subtraction

[1] 0

In [3]:
2*2 # Multiplication

[1] 4

In [4]:
2/2 # Division

[1] 1

In [5]:
3^2 # Square of three

[1] 9

In [6]:
sqrt(2) #Square root

[1] 1.414214

In [7]:
5%%2 #remainder

[1] 1

In [8]:
log(2) #logarithm

[1] 0.6931472

## Operators precedence

In [10]:
5+2*3

[1] 11

In [11]:
(5+2)*3

[1] 21

In [14]:
5*5/2+3

[1] 15.5

## Relational operators

In [15]:
5 > 7

[1] FALSE

In [16]:
5 < 7

[1] TRUE

In [17]:
5 >= 5

[1] TRUE

In [18]:
5 <= 5

[1] TRUE

In [19]:
5 == 5

[1] TRUE

## Logical operations

In [20]:
! TRUE

[1] FALSE

In [21]:
TRUE & FALSE

[1] FALSE

In [22]:
TRUE | FALSE

[1] TRUE

## Entering input

In [23]:
answer  <- 1+2 # shortcut: alt -

In [24]:
print(answer)

[1] 3


## Evaluation

In [25]:
print(answer)

[1] 3


In [27]:
x  <- 1:40
print(x)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40


## Object

In [30]:
w  <- 5L
x <- 5
y <- "Hello, world!"
z <- c(1, 2, 3)

In [31]:
class(w)
class(x)
class(y)
class(z)

[1] "integer"

[1] "numeric"

[1] "character"

[1] "numeric"

## Infinity

In [33]:
1/Inf

[1] 0

In [34]:
Inf + Inf

[1] Inf

## Vectors

In [36]:
a <- c(0.5, 0.6)       ## numeric
b <- c(TRUE, FALSE)    ## logical
c <- c(T, F)           ## logical
d <- c("a", "b", "c")  ## character
e <- 9:29              ## integer
f <- c(1+0i, 2+4i)     ## complex


## Recycling

In [38]:
x <- c(1, 2, 3)
y <- c(10, 20, 30, 40, 50, 60, 70)
x+y

Warning message in x + y:
"longer object length is not a multiple of shorter object length"


[1] 11 22 33 41 52 63 71

## Vector Rescaling

In [39]:
inches <- c(69, 62, 66, 70, 70, 73, 67, 73, 67, 70)

In [43]:
cm  <- inches * 2.54
cm

[1] 175.26 157.48 167.64 177.80 177.80 185.42 170.18 185.42 170.18 177.80

In [44]:
cm - 100

[1] 75.26 57.48 67.64 77.80 77.80 85.42 70.18 85.42 70.18 77.80

## Implicit Coercion

In [46]:
a <- c(1.7, "a")   ## character
a
class(a)

[1] "1.7" "a"

[1] "character"

In [47]:
b <- c(TRUE, 2)
b
class(b)

[1] 1 2

[1] "numeric"

In [48]:
c <- c("a", TRUE)
c
class(c)

[1] "a"    "TRUE"

[1] "character"

## Explicit Coercion

In [55]:
a  <- 0:6
a

[1] 0 1 2 3 4 5 6

In [56]:
class(a)

[1] "integer"

In [57]:
x  <- as.numeric(a)
x
class(x)

[1] 0 1 2 3 4 5 6

[1] "numeric"

In [58]:
y  <- as.logical(a)
y
class(y)

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

[1] "logical"

In [59]:
z  <- as.character(a)
z
class(z)

[1] "0" "1" "2" "3" "4" "5" "6"

[1] "character"

## Not Available

In [60]:
x <- c("a", "b", "c")
as.numeric(x)


Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"


[1] NA NA NA

In [61]:
as.logical(x)

[1] NA NA NA

In [62]:
as.complex(x)

Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"


[1] NA NA NA

## Matrix

In [63]:
m <- matrix(1:6, nrow = 2, ncol = 3) 
m


[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [64]:
attributes(m)

$dim
[1] 2 3

## Vector to matrix

In [69]:
m  <- 1:10
m
dim(m)

[1]  1  2  3  4  5  6  7  8  9 10

NULL

In [70]:
dim(m)  <- c(2,5)
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

## Binding

In [73]:
x <- 1:3
y <- 10:12

In [74]:
cbind(x, y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

In [72]:
rbind(x,y)

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

## Lists

In [75]:
x <- list(1, "a", TRUE, 1 + 4i) 
x

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1+4i

## Factors

In [77]:
x <- factor(c("yes", "yes", "no", "yes", "no")) 
x

[1] yes yes no  yes no 
Levels: no yes

In [78]:
table(x)

x
 no yes 
  2   3 

In [79]:
unclass(x)

[1] 2 2 1 2 1
attr(,"levels")
[1] "no"  "yes"

## Missing Values

In [80]:
x <- c(1, 2, NaN, NA, 4)
is.na(x)

[1] FALSE FALSE  TRUE  TRUE FALSE

In [81]:
is.nan(x)

[1] FALSE FALSE  TRUE FALSE FALSE

## Dataframe

In [82]:
x <- data.frame(foo = 1:4, bar = c(T, T, F, F)) 
x

foo bar  
1 1    TRUE
2 2    TRUE
3 3   FALSE
4 4   FALSE

In [83]:
nrow(x)

[1] 4

In [84]:
ncol(x)

[1] 2

## Names

In [85]:
codes <- c(italy = 380, canada = 124, egypt = 818)
codes


italy canada  egypt 
   380    124    818

In [89]:
codes <- c(380, 124, 818)
codes

[1] 380 124 818

In [90]:
country <- c("italy","canada","egypt")
names(codes) <- country
codes

italy canada  egypt 
   380    124    818

## Sequences

In [91]:
seq(1,10)

[1]  1  2  3  4  5  6  7  8  9 10

In [92]:
seq(1,10,2)

[1] 1 3 5 7 9

In [94]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

## Subsetting

In [95]:
codes

italy canada  egypt 
   380    124    818

In [96]:
codes[2]

canada 
   124

In [97]:
codes[c(1,3)]

italy egypt 
  380   818

In [98]:
codes[1:2]

italy canada 
   380    124

In [99]:
codes["canada"]

canada 
   124

In [100]:
codes[c("egypt",'italy')]

egypt italy 
  818   380

## Conditional statements

- if and else: testing a condition and acting on it
- for: execute a loop a fixed number of times
- while: execute a loop while a condition is true
- repeat: execute an infinite loop (must break out of it to stop)
- break: break the execution of a loop
- next: skip an interation of a loop

## If statement

In [102]:
a  <- 0

In [103]:
if(a!=0){
     print(1/a)
} else{
     print("No reciprocal for 0.")
}

[1] "No reciprocal for 0."


## If, else if, else

In [104]:
x <- 0

if (x < 0) { 
    print("Negative number")
} else if (x > 0) { 
    print("Positive number") 
} else 
print("Zero") 

[1] "Zero"


## Ifelse

In [105]:
a <- 0
ifelse(a > 0, 1/a,"No reciprocal for 0.")

[1] "No reciprocal for 0."

In [106]:
a <- c(0, 1, 2, -4, 5)

result <- ifelse(a > 0, 1/a, NA)

result

[1]  NA 1.0 0.5  NA 0.2

## For Loops

In [107]:
for (i in 1:10){
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [108]:
x <- c("a", "b", "c", "d")

In [109]:
for(i in 1:4) {
        print(x[i])  
 }

[1] "a"
[1] "b"
[1] "c"
[1] "d"


In [110]:
for(i in seq_along(x)) {   
         print(x[i])
 }

[1] "a"
[1] "b"
[1] "c"
[1] "d"


## Nested for loops

In [111]:
x <- matrix(1:6, 2, 3)

In [112]:
for(i in seq_len(nrow(x))) {
        for(j in seq_len(ncol(x))) {
                print(x[i, j])
        }   
}

[1] 1
[1] 3
[1] 5
[1] 2
[1] 4
[1] 6


## While loop

In [114]:
count <- 0

In [115]:
while(count < 10) {
         print(count)
       count <- count + 1
}

[1] 0
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9


## Next

In [117]:
for (i in 1:5) {
  if (i == 3) {
    next  
  }
  print(i)
}

[1] 1
[1] 2
[1] 4
[1] 5


## Break

In [118]:
for (i in 1:5) {
  if (i == 3) {
    break  
  }
  print(i)
}

[1] 1
[1] 2


## Help

In [119]:
help('log') #opens a new window

In [120]:
?log #opens a new window

In [121]:
args(log)

function (x, base = exp(1)) 
NULL

## Function arguments

In [122]:
log(8)

[1] 2.079442

In [123]:
log(8,base=2)

[1] 3

In [124]:
log(base=2, x=8)

[1] 3

In [125]:
log(8,2)

[1] 3

## Creating functions

In [126]:
avg  <- function(x){
    s <- sum(x)
    n  <-  length(x)
    s/n
}

In [127]:
x  <- 1:100

In [128]:
avg(x)

[1] 50.5

In [129]:
mean(x)

[1] 50.5

In [130]:
identical(mean(x),avg(x))

[1] TRUE

In [131]:
remainder <- function(num, divisor = 2) {
  # Remember: the last expression evaluated will be returned! 
  num %% divisor
}

In [132]:
remainder(7)

[1] 1

In [134]:
remainder(8,3)

[1] 2

In [137]:
evaluate <- function(func, data){
func(data)
}

In [136]:
evaluate(mean,c(1,2,3))

[1] 2

## Anonymous function

In [139]:
evaluate(function(x)  {x+1}, 6)

[1] 7

In [140]:
evaluate(function(x)  {x[length(x)]}, c(8, 4, 100))

[1] 100

## Paste function

In [142]:
paste('R','Cheat','Sheet')

[1] "R Cheat Sheet"

In [143]:
paste

function (..., sep = " ", collapse = NULL, recycle0 = FALSE) 
.Internal(paste(list(...), sep, collapse, recycle0))
<bytecode: 0x0000000012f1bde8>
<environment: namespace:base>

## additional arguments

In [145]:
msg  <- function(...){
    paste('hi',...,'bye')
}

In [146]:
msg("R","Cheat","sheet")

[1] "hi R Cheat sheet bye"